"""Confidence Cascade (L7): deterministic thresholds + locked-option escalation."""

from .cascade import CascadeDecision, apply_confidence_cascade
from .escalation import (
    ACCEPT,
    CASCADE_TIERS,
    DISPOSITIONS,
    ENTRY_CONDITIONS,
    ESCALATE,
    ESCALATION_CONTRACT_VERSION,
    REJECT,
    TIER_ADJUDICATOR,
    TIER_CRITIC,
    TIER_DETERMINISTIC,
    UNRESOLVED_DISPOSITION,
    CascadeReport,
    EscalationDecision,
    EscalationDecisionSource,
    EscalationRequest,
    EscalationValidationResult,
    EvidenceBundle,
    LockedAssertionOption,
    LockedBoundaryOption,
    LockedCandidateOption,
    LockedOptionSet,
    LockedTypeOption,
    build_escalation_request,
    build_locked_options,
    deterministic_fallback,
    evaluate_entry_conditions,
    resolve_escalation,
    run_cascade_escalation,
    validate_escalation_decision,
)

__all__ = [
    "ACCEPT",
    "CASCADE_TIERS",
    "DISPOSITIONS",
    "ENTRY_CONDITIONS",
    "ESCALATE",
    "ESCALATION_CONTRACT_VERSION",
    "REJECT",
    "TIER_ADJUDICATOR",
    "TIER_CRITIC",
    "TIER_DETERMINISTIC",
    "UNRESOLVED_DISPOSITION",
    "CascadeDecision",
    "CascadeReport",
    "EscalationDecision",
    "EscalationDecisionSource",
    "EscalationRequest",
    "EscalationValidationResult",
    "EvidenceBundle",
    "LockedAssertionOption",
    "LockedBoundaryOption",
    "LockedCandidateOption",
    "LockedOptionSet",
    "LockedTypeOption",
    "apply_confidence_cascade",
    "build_escalation_request",
    "build_locked_options",
    "deterministic_fallback",
    "evaluate_entry_conditions",
    "resolve_escalation",
    "run_cascade_escalation",
    "validate_escalation_decision",
]
